Add allowCountries param
LeleDerGrasshalmi/FortniteEndpointsDocumentation pull request #334
Opened 2024-11-01 13:31 UTC by Snailedlt

## PR Checklist

- [x] I have properly named the PR
- [x] I have described why this change should be merged (why is this change useful/good)
- [x] I have followed the [Contribution Guide / Formatting](https://github.com/LeleDerGrasshalmi/FortniteEndpointsDocumentation/blob/main/CONTRIBUTING.md)

## Change Description

There was a missing parameter. I'm unsure exactly what the parameter does, but it seems like both allowCountries and country affect which games are shown. `country` also affects which currency is used.

So example calls that showcase the differences:
| URL | Note |
| ----- | ----- |
| https://store-site-backend-static-ipv4.ak.epicgames.com/freeGamesPromotions?locale=en-US&country=NO&allowCountries=NO | Currency is NOK and Ghostwire is shown since it is available in Norway |
| https://store-site-backend-static-ipv4.ak.epicgames.com/freeGamesPromotions?locale=en-US&country=NO&allowCountries=RU | Currency is also NOK, but some games (for example Ghostwire) aren't shown since the allowCountries is Russia. |
| https://store-site-backend-static-ipv4.ak.epicgames.com/freeGamesPromotions?locale=en-US&country=RU&allowCountries=RU | Currency is RUB and Ghostwire isn't shown |
| https://store-site-backend-static-ipv4.ak.epicgames.com/freeGamesPromotions?locale=en-US&country=RU&allowCountries=NO | Here the currency is RUB but Ghostwire is shown, since Ghostwire is available in Norway |

2024-11-01 13:32 UTC, Snailedlt commented on EpicGamesStore/FreePromos.md
> +`allowCountries`: Show all promos available in the requested Countries
```suggestion
`country`: Determines the price and which currency is shown
`allowCountries`: Show all promos available in the requested Countries
```

2024-11-01 13:35 UTC, Snailedlt commented
Sidenote: Are there any API endpoints you know of that can fetch all historical free games?

2024-11-10 16:31 UTC, LeleDerGrasshalmi commented
> Sidenote: Are there any API endpoints you know of that can fetch all historical free games?

nope, there is **no public** api for that ):

2024-11-10 16:44 UTC, LeleDerGrasshalmi requested changes
you forgot a newline break, so its broken now
![image](https://github.com/user-attachments/assets/b8f15a31-29fd-4cbb-a7a1-ba19e5cbc724)

2024-11-10 18:31 UTC, Snailedlt commented on EpicGamesStore/FreePromos.md
> +`country`: Determines the price and which currency is shown
```suggestion
`country`: Determines the price and which currency is shown<br/>
```

2024-11-10 18:39 UTC, Snailedlt commented
@LeleDerGrasshalmi fixed

2024-11-15 22:27 UTC, LeleDerGrasshalmi approved these changes

2024-11-15 22:27 UTC, merged